[package]
name = "dom_api"
description = "Dom (Berg) Rest API"
license = "GPL-3.0"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
